### ISSUE TITLE
Impossible d'ajouter des "info" manuellement

### ISSUE THREAD

**Issue by doudz** [lunarok/jeedom_MQTT#11]
Lorsqu'on souhaite créer/modifier manuellement un objet il est uniquement possible d'ajouter des actions mais pas des infos.
Ceci est problématique lorsque la découverte automatique génère plusieurs objets au lieu d'un seul

C'est le cas si on utilise mysensors en mode mqtt, la découverte automatique de découpe pas les topics comme il faudrait.

**Comment by lunarok** [comment]
Vu l'autre issue le découpage est normal, c'est le format mySensors qui l'est pas
Il n'y a pas besoin de créer des commandes infos normalement
