### ISSUE TITLE
La découverte automatique ne tient pas compte des topics des objets existants

### ISSUE THREAD

**Issue by doudz** [lunarok/jeedom_MQTT#12]
Lorsque j'utilise mysensors en mqtt, les messages sont du style :

Pour le node ID 2 :

mysensors-out/2/0/0/0/6 
mysensors-out/2/255/0/0/17 2.0.0
mysensors-out/2/255/3/0/11 Temperature sensor
mysensors-out/2/255/3/0/12 1.1
mysensors-out/2/0/1/0/0 20.2

Actuellement en mode automatique le plugin génère plusieurs objets, un avec le topic mysensors-out/2/0/0 puis un autre avec mysensors-out/2/255/0 puis encore un autre mysensors-out/2/0/1/0

Il faudrait pouvoir créer manuellement un objet avec le subscribe topic mysensors-out/2 par exemple et que par conséquent, en mode automatique, toutes les infos aillent dans cet objet

**Comment by doudz** [comment]
En regardant le code d'un peu plus prêt je me rends compte que le système de tient pas compte du champ "Inscrit au Topic" puis en fait il se base sur le LogicalId qui est masqué et non modifiable

**Comment by lunarok** [comment]
Inscrit au topic c'est pour le mode manuel
Pas possible de palier tous les arbos d'envois, la il faut passer en manuel. MySensors devrait laisser la possibilité de choisir le format de publication car la forcément c'est pas commun

**Comment by doudz** [comment]
Je comprends mais le mode manuel devrait donc laisser la possibilité de créer manuellement les infos (voir l'autre issue)

**Comment by KipK** [comment]
Yes. Je n'ai pas rajouté les infos en mode manuel dans mon patch mais je me
rend compte aussi que ca serait utile.
Je ne suis toujours pas rentré de vacances, mais je peux m'en occuper a mon
retour dans quelques jours.

**Comment by KipK** [comment]
Salut.

Bon j'ai essayé de rajouter l'ajout manuel des infos. Le seul intérêt étant d'aller chercher des sous topics  , mais soucis, dans ce cas là, ça plante sur cette ligne
$cmdlogic = MQTTCmd::byEqLogicIdAndLogicalId($elogic->getId(),$cmdId);
vu que le cmdId correspond au dernier répertoire du chemin, dans le cas d'un sous topic il ne reconnait donc pas le getId() auquel on l'a rattaché à la création du champs.

Il faudrait revoir un peu la manière dont le plugin fonctionne en l'état, mais c'est pas un petit changement j'ai l'impression, pas sûr que je puisse faire grand chose à mon niveau très sommaire.
