### ISSUE TITLE
Impossible de changer le "type" d'une info découverte

### ISSUE THREAD

**Issue by doudz** [lunarok/jeedom_MQTT#13]
Lorsqu'une info est découverte automatiquement, il est impossible de changer le type (Numérique, Binaire, Autre) car le champ est absent.
Il faut modifier la ligne en question, par exemple ajouter l'unité, et enregistrer pour voir le champ "type" apparaître et donc pouvoir le modifier.

**Comment by KipK** [comment]
bizarrement, le drop down menu était commenté. Je l'ai dé-commenté dans mon pull request pour l'option retain sur chaque commande.

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_MQTT/commit/f0a9328b383661c053d73db22d1574014a3185a4

merge
