### ISSUE TITLE
missing adding command info in the creating command screen

### ISSUE THREAD

**Issue by eciruam35** [lunarok/jeedom_MQTT#16]
To be able to add an info without activating "automatic device discover" in configuration:
The following lines are missing: in desktop/php/MQTT.php after L247

> 

<fieldset>

            <div class="form-actions">
              <a class="btn btn-success btn-sm cmdInfo" id="bt_addMQTTInfo"><i class="fa fa-plus-circle"></i> {{Ajouter une commande Info}}</a>
            </div>

</fieldset>

> 

and in desktop/js/MQTT.js file 
Line 79 et 81 remove "ReadOnly=true"

**Comment by lunarok** [comment]
cannot accept, I support only automatic mode
will not implement breaking things in automatic mode like that for manual, do a PR for manual or use the plugin as it's supported
