### ISSUE TITLE
In manual mode there is no info refresh

### ISSUE THREAD

**Issue by eciruam35** [lunarok/jeedom_MQTT#17]
If I set off "Decouverte Automatique des topics:" there is no info refresh.
it seems that when removing disable and realonly of the following line:

> 					<label class="checkbox-inline"><input id="isChild" type="checkbox" class="eqLogicAttr" data-l1key="configuration" data-l2key="isChild" disabled readonly /></label>

> 
and when we unset the "Topic Enfant" it seems OK , the info data are read in the broker in manual mode

**Comment by lunarok** [comment]
not needed for automatic
