### ISSUE TITLE
the config parameter are not read

### ISSUE THREAD

**Issue by eciruam35** [lunarok/jeedom_MQTT#18]
> 
    public static function daemon() {

    $mosqHost = config::byKey('mqttAdress', 'MQTT', 0);
    $mosqPort = config::byKey('mqttPort', 'MQTT', 0);
    $mosqId = config::byKey('mqttId', 'MQTT', 0);
	$mosqTopic = config::byKey('mqttTopic', 'MQTT', 0);
	$mosqQos = config::byKey('mqttQos', 'MQTT', 0);
    log::add('MQTT', 'debug', 'DAEMON_MD ');

    log::add('MQTT', 'info', 'DAEMON_MD0 Host : ' . $mosqHost . ', Port : ' . $mosqPort . ', ID : ' . $mosqId .    ', Topic : ' . $mosqTopic);
> 

LOG:

> 
     [2017-02-12 08:39:16][DEBUG] : DAEMON_MD
     [2017-02-12 08:39:16][INFO] : DAEMON_MD0 Host : 0, Port : 0, ID : 0, Topic : 0

>

**Comment by lunarok** [comment]
?
