### ISSUE TITLE
Détection automatique qui ne fonctionne plus

### ISSUE THREAD

**Issue by florian-guillemard** [lunarok/jeedom_MQTT#20]
Bonjour,

J'ai un serveur MQTT, mon jeedom se connecte dessus et envoie correctement toutes les commandes. J'avais la détection automatique qui fonctionnait à merveille, ça me rajoutait donc les commandes "info" automatiquement dès la première réception..

Depuis quelques jours, je m'amuse à développer un appareil qui se connecte sur mon serveur MQTT, le plugin avait bien détecté les commandes "info" reçu sur le serveur sauf que aujourd'hui, pour une raison que j'ignore, impossible de refaire marché la détection automatique.

J'ai essayé : 
 - la désactivation et réactivation de l'option dans les paramètres de configuration,
 - la réinstallation du plugin et des dépendances,
 - l'ajout d'une nouvelle commande "info" via MQTT.fx

Rien n'y fait, ça ne fonctionne plus :(

Merci de m'indiquer ce que je peux essayer!

Bonne journée,

Pour info, je suis sous Jeedom 3.1.7 et le plugin MQTT "2017-10-04 01:03:41"

**Comment by florian-guillemard** [comment]
Je viens de restaurer un backup d'avant mes tests, et il s'avère que c'est pareil :(

**Comment by SuperToma** [comment]
Tu as accès à ta machine Jeedom en SSH ?

**Comment by florian-guillemard** [comment]
Oui

**Comment by lunarok** [comment]
tu peux aller sur le forum stp, les issues ici je les prend pour des bugs, pas pour faire du support, merci
