### ISSUE TITLE
Jeedom 3.1.7 et Debian 9

### ISSUE THREAD

**Issue by Czara** [lunarok/jeedom_MQTT#21]
Impossible d'installer les dépendances automatiquement.
Après récupération du script install.sh, j'ai entré les commandes à la main, le problème vient du fait que Debian 9 ne possède pas de paquet php5-dev ou php7-dev. Il faut installer le package php-dev. 

Voici les logs : 

Début d'installation des dépendances
Reading package lists...
Building dependency tree...
Reading state information...
lsb-release is already the newest version (9.20161125).
php-pear is already the newest version (1:1.10.1+submodules+notgz-9).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
--2017-10-15 15:58:15--  http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
Resolving repo.mosquitto.org (repo.mosquitto.org)... 85.119.83.194, 2001:ba8:1f1:f271::2
Connecting to repo.mosquitto.org (repo.mosquitto.org)|85.119.83.194|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3137 (3.1K) [application/octet-stream]
Saving to: 'mosquitto-repo.gpg.key.6'

     0K ...                                                   100% 4.20M=0.001s

2017-10-15 15:58:15 (4.20 MB/s) - 'mosquitto-repo.gpg.key.6' saved [3137/3137]

Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://deb.debian.org/debian stretch-updates InRelease
Hit:3 http://security.debian.org stretch/updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Hit:5 https://deb.nodesource.com/node_5.x jessie InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php5-dev
Fin installation des dépendances

**Comment by lunarok** [comment]
voir la doc
