### ISSUE TITLE
Connections Lost sur double publication

### ISSUE THREAD

**Issue by flotre** [lunarok/jeedom_MQTT#23]
Par défaut, mosquitto deconnecte un client mqtt si celui ci se connecte 2 fois de suite. Cela pose problème chez moi car il m'arrive souvent d'avoir plusieurs commandes qui sont envoyées en même temps . Du coup, il y a une connexion pour chaque commande et si la connexion précédente n'est pas terminée, une des 2 commandes échouent car elle se fait déconnecter par l'autre.
Du coup il faut soit gérer les commandes dans une fifo pour être sûr de ne pas en avoir 2 en // ou mettre un nom client différent pour chaque commande.

**Comment by lunarok** [comment]
Tu peux essayer https://github.com/lunarok/jeedom_MQTT/commit/e64fba1bb4579f94c8ab0d717a64c4f424b4bb31 ?

**Comment by flotre** [comment]
j'ai patché le plugin, je te fais un retour dans 24h. En général, j'ai toujours au moins une erreur en 24h.

**Comment by flotre** [comment]
la correction fonctionne. 2 clients qui publient peuvent se connecter en meme temps.
merci

extrait du log de mosquitto:
1515736809: New connection from 127.0.0.1 on port 1883.
1515736809: New client connected from 127.0.0.1 as Jeedom_pub_450 (c1, k60, u'jeedom').
1515736809: New connection from 127.0.0.1 on port 1883.
1515736809: New client connected from 127.0.0.1 as Jeedom_pub_373 (c1, k60, u'jeedom').
1515736810: Client Jeedom_pub_450 disconnected.
1515736810: Client Jeedom_pub_373 disconnected.
