### ISSUE TITLE
erreur doc / docs

### ISSUE THREAD

**Issue by Th3ju** [lunarok/jeedom_MQTT#25]
Bonjour Lunarok,

Je découvre ton plugin et j'ai une petite erreur sur mon installation toute neuve du plugin. 
Je n'ai pas d'affichage des images quand je choisi une icone de topic.

Si on regarde de plus près, le lien est fait sur /plugins/MQTT/**doc**/images/node_relay.png  alors que sur mon installation, le plugin contient un repertoires doc**s**

Si je fait une copie de docs vers doc, tout rentre dans l'ordre.

Encore merci pour le plugin

Juju

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_MQTT/commit/4c069ffc43ac00bfaa1b4c32c45eee0a5fd2f9fe
