### ISSUE TITLE
Echec de détection des dépendances

### ISSUE THREAD

**Issue by pierre-dominique** [lunarok/jeedom_MQTT#29]
https://github.com/lunarok/jeedom_MQTT/blob/693fcb1143085be41001d02fd6159781f4b07d46/core/class/MQTT.class.php#L74
```
$cmd = "which mosquitto | wc -l";
    exec($cmd, $output, $return_var);
```

si le user www-data n'est pas autorisé à lancer dpkg ($return_var = 1 et $output = '') ce test ne fonctionne pas avec un "which mosquitto | wc -l" on aurait le même test avec moins de droits nécessaires.

**Comment by neissa** [comment]
up

**Comment by lunarok** [comment]
standard dans jeedom, l'utilisateur www-data est utilisé pour ce genre de commandes dans de nombreux plugins
