### ISSUE TITLE
json message don't decoded correctly

### ISSUE THREAD

**Issue by sriccardi-invn** [lunarok/jeedom_MQTT#30]
Connected TH16 with temperature sensor and loaded TasmotaFirmware.
Topic SENSOR is not interpreted correctly and we cannot get temperature
I tested with another tool on PC and I get this message:
{"Time":"2019-10-19T16:29:18","DS18B20":{"Temperature":18.5},"TempUnit":"C"}.
Th MQTT plugn can get Time and TempUnit but not the Temperature

**Comment by lunarok** [comment]
nested json are not supported
