### ISSUE TITLE
Récupérer la valeur d'une commande venant d'un autre device/plugin

### ISSUE THREAD

**Issue by KipK** [lunarok/jeedom_MQTT#8]
Salut

Je bloque sur un truc sûrement très bête.
Je cherche à envoyer une valeur de commande depuis un device du plugin Virtuel
du type:

Dans mon virtual j'ai une commande action:
Action: #[MQTT][Climat][cmd1]#
Valeur:  NOT[MQTT][Climat]][Etat]

avec #[MQTT][Climat][cmd1]# qui est la commande de mon device MQTT.

Quelle serait la syntaxe dans le champs valeur de mon action coté plugin MQTT pour pourvoir récupérer la valeur de la commande du virtual qui l'a appelé ?

Sinon que devrais-je modifier au plugin pour pouvoir activer une telle fonctionnalité ? 
Je ne vois pas d'exemple pour récupérer la valeur d'une commande appelée par un élement externe.

Merci à toi

**Comment by lunarok** [comment]
Les issues ne sont pas une FAQ
Le problème est pris à l'envers, classiquement on activera la commande en envoyant la valeur voulue depuis un scénario ou un virtuel

**Comment by KipK** [comment]
Ce n'est pas vraiment une question type FAQ, plus une question de developpement voir bug report.

Si je regarde avec le plugin virtuel uniquement, on peut faire passer des valeurs d'une commande à une autre ( d'un virtuel à l'autre ).
Cf un slider ou message, la valeur arrive bien sur la commande appellée.

Par contre avec le plugin MQTT la valeur n'arrive pas sur la commande appellée, elle reste nulle. 
J'essaye de fixer le code justement pour résoudre ce soucis. Mais je ne trouve pas d'où  viens le problème.

**Comment by lunarok** [comment]
virtuel est un cas particulier justement fait pour ca
ce n'est pas standard jeedom la demande, donc non

**Comment by KipK** [comment]
Je me suis peut être mal exprimé, pour être plus clair voici un exemple:

Entre 2 Virtuels:
[virtuel1][cmd] : Virtuel 1 a une commande [cmd] , de type slider, qui affiche le resultat dans le champs info [Etat]
[virtuel2][cmd]: Virtuel 2 a une commande [cmd] de type slider aussi, qui appelle [virtuel1][cmd] avec la valeur du slider.
RESULTAT: la valeur du slider de [virtuel1] s'affiche bien dans [virtuel2][Etat]

Par contre entre 1 Virtuel et un Mqtt:
[virtuel1][cmd] : Virtuel 1 a une commande [cmd] , de type slider, qui affiche le resultat dans le champs info [Etat]
[mqtt1][cmd] mqtt1 a une commande [cmd] de type slider, qui publie sur le topic /mqtt1/cmd et son champs Valeur est laissé nul volontairement pour être remplis par la commande qui l'appelle.

Resultat: mqtt1 publie sur le topic  avec une valeur null

Si on peut le faire avec un virtuel je dois pouvoir modifier un peu le code du plugin mqtt pour faire la même chose non ? 

Même pas une petite piste pour m'orienter ? Tu penses que c'est impossible ? 

J'épluche le code de jeedom petit à petit mais c'est un peu compliqué car il y a très peu de doc développeur sur ce projet. L'avis d'un habitué m'interesse.

**Comment by lunarok** [comment]
Faut pas laisser à vide une valeur de slider forcément il peut pas faire le substitute
Point déjà abordé sur le forum, là aussi standard jeedom
Non le plugin ne fera pas les fonctionnalités de virtuels

**Comment by KipK** [comment]
Désolé d'insister, J'ai du mal à comprendre ta réponse car entre ta première phrase et la dernière je l'entend comme des contraires.

> Faut pas laisser à vide une valeur de slider forcément il peut pas faire le substitute
> Point déjà abordé sur le forum, là aussi standard jeedom 

  Du coup tu veux dire qu'il y a une syntaxe pour faire le substitue d'une valeur récupérée par un appel de commande ? 
Dan ce cas là c'est justement ce que je cherche à faire

> Non le plugin ne fera pas les fonctionnalités de virtuels 

Là je te suis plus :)

Si tu ne veux pas que je soumette cette feature sur le git je n'y vois aucun soucis, mais si je veux rajouter ça de mon coté quel est le problème ? Je demande juste une piste après je me débrouille ;)

Ou alors tu veux dire que c'est clairement impossible sans modifier le core de jeedom pour l'instant ? 
Merci
